# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:

services:
  db:
    container_name: db 
    build:
      context: ./postgresql
      dockerfile: .//Dockerfile
      args:
        - DS_RO_PASS=1234
        - POSTGRES_PASSWORD=1234
    environment:
      - DS_RO_PASS=1234
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: ./solr
      dockerfile: ./Dockerfile
  
  ckan:
    container_name: ckan
    build:
      context: ./ckan
    links:
      - db
    ports:
      - "0.0.0.0:5000:5000"

    volumes:
      - ckan_config:/usr/lib/ckan/default/config/
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
